package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

/**
 * AspNetUserTokens generated by hbm2java
 */
@Entity
@Table(name = "AspNetUserTokens", schema = "dbo", catalog = "onlineaccounting")
public class AspNetUserTokens implements java.io.Serializable {

	private AspNetUserTokensId id;

	public AspNetUserTokens() {
	}

	public AspNetUserTokens(AspNetUserTokensId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false)),
			@AttributeOverride(name = "loginProvider", column = @Column(name = "LoginProvider", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "Name", nullable = false)),
			@AttributeOverride(name = "value", column = @Column(name = "Value")) })
	public AspNetUserTokensId getId() {
		return this.id;
	}

	public void setId(AspNetUserTokensId id) {
		this.id = id;
	}

}
