package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;

/**
 * AspNetUserClaims generated by hbm2java
 */
@Entity
@Table(name = "AspNetUserClaims", schema = "dbo", catalog = "onlineaccounting")
public class AspNetUserClaims implements java.io.Serializable {

	private int id;
	private AspNetUsers aspNetUsers;
	private String claimType;
	private String claimValue;

	public AspNetUserClaims() {
	}

	public AspNetUserClaims(int id, AspNetUsers aspNetUsers) {
		this.id = id;
		this.aspNetUsers = aspNetUsers;
	}

	public AspNetUserClaims(int id, AspNetUsers aspNetUsers, String claimType, String claimValue) {
		this.id = id;
		this.aspNetUsers = aspNetUsers;
		this.claimType = claimType;
		this.claimValue = claimValue;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public AspNetUsers getAspNetUsers() {
		return this.aspNetUsers;
	}

	public void setAspNetUsers(AspNetUsers aspNetUsers) {
		this.aspNetUsers = aspNetUsers;
	}

	@Column(name = "ClaimType")
	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	@Column(name = "ClaimValue")
	public String getClaimValue() {
		return this.claimValue;
	}

	public void setClaimValue(String claimValue) {
		this.claimValue = claimValue;
	}

}
