package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerDiscount generated by hbm2java
 */
@Entity
@Table(name = "CustomerDiscount", schema = "dbo", catalog = "onlineaccounting")
public class CustomerDiscount implements java.io.Serializable {

	private int id;
	private Customer customer;
	private Product product;
	private Date insertedAt;
	private BigDecimal rate;
	private boolean active;

	public CustomerDiscount() {
	}

	public CustomerDiscount(int id, Customer customer, Product product, Date insertedAt, BigDecimal rate,
			boolean active) {
		this.id = id;
		this.customer = customer;
		this.product = product;
		this.insertedAt = insertedAt;
		this.rate = rate;
		this.active = active;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertedAt", nullable = false, length = 19)
	public Date getInsertedAt() {
		return this.insertedAt;
	}

	public void setInsertedAt(Date insertedAt) {
		this.insertedAt = insertedAt;
	}

	@Column(name = "Rate", nullable = false, precision = 9)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
