package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;
import java.util.Date;

/**
 * EmployeeAddress generated by hbm2java
 */
@Entity
@Table(name = "EmployeeAddress", schema = "dbo", catalog = "onlineaccounting")
public class EmployeeAddress implements java.io.Serializable {

	private int id;
	private Address address;
	private Employee employee;
	private String description;
	private Date lastUpdate;
	private boolean active;

	public EmployeeAddress() {
	}

	public EmployeeAddress(int id, Address address, Employee employee, String description, Date lastUpdate,
						   boolean active) {
		this.id = id;
		this.address = address;
		this.employee = employee;
		this.description = description;
		this.lastUpdate = lastUpdate;
		this.active = active;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AddressId", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EmployeeId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
