package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;
import java.util.Date;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "ProductAttribute", schema = "dbo", catalog = "onlineaccounting")
public class ProductAttribute implements java.io.Serializable {

	private int id;
	private Product product;
	private ProductProperty productProperty;
	private Date insertedAt;
	private boolean active;

	public ProductAttribute() {
	}

	public ProductAttribute(int id, Product product, ProductProperty productProperty, Date insertedAt, boolean active) {
		this.id = id;
		this.product = product;
		this.productProperty = productProperty;
		this.insertedAt = insertedAt;
		this.active = active;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductPropertyId", nullable = false)
	public ProductProperty getProductProperty() {
		return this.productProperty;
	}

	public void setProductProperty(ProductProperty productProperty) {
		this.productProperty = productProperty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertedAt", nullable = false, length = 19)
	public Date getInsertedAt() {
		return this.insertedAt;
	}

	public void setInsertedAt(Date insertedAt) {
		this.insertedAt = insertedAt;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
