package com.bakery.management.model.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "Vehicle", schema = "dbo", catalog = "onlineaccounting")
public class Vehicle implements java.io.Serializable {

	private int id;
	private Merchant merchant;
	private String plateNumber;
	private Date assesmentDate;
	private Date assuranceRenewalDate;
	private boolean outOfOrderFlag;
	private Character serviceType;
	private Date lastUpdate;
	private boolean active;
	private Set<VehicleDriver> vehicleDrivers = new HashSet<>(0);

	public Vehicle() {
	}

	public Vehicle(int id, Merchant merchant, String plateNumber, Date assesmentDate, boolean outOfOrderFlag,
			Date lastUpdate, boolean active) {
		this.id = id;
		this.merchant = merchant;
		this.plateNumber = plateNumber;
		this.assesmentDate = assesmentDate;
		this.outOfOrderFlag = outOfOrderFlag;
		this.lastUpdate = lastUpdate;
		this.active = active;
	}

	public Vehicle(int id, Merchant merchant, String plateNumber, Date assesmentDate, Date assuranceRenewalDate,
			boolean outOfOrderFlag, Character serviceType, Date lastUpdate, boolean active, Set<VehicleDriver> vehicleDrivers) {
		this.id = id;
		this.merchant = merchant;
		this.plateNumber = plateNumber;
		this.assesmentDate = assesmentDate;
		this.assuranceRenewalDate = assuranceRenewalDate;
		this.outOfOrderFlag = outOfOrderFlag;
		this.serviceType = serviceType;
		this.lastUpdate = lastUpdate;
		this.active = active;
		this.vehicleDrivers = vehicleDrivers;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MerchantId", nullable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@Column(name = "PlateNumber", nullable = false, length = 15)
	public String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AssesmentDate", nullable = false, length = 10)
	public Date getAssesmentDate() {
		return this.assesmentDate;
	}

	public void setAssesmentDate(Date assesmentDate) {
		this.assesmentDate = assesmentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AssuranceRenewalDate", length = 10)
	public Date getAssuranceRenewalDate() {
		return this.assuranceRenewalDate;
	}

	public void setAssuranceRenewalDate(Date assuranceRenewalDate) {
		this.assuranceRenewalDate = assuranceRenewalDate;
	}

	@Column(name = "OutOfOrderFlag", nullable = false)
	public boolean isOutOfOrderFlag() {
		return this.outOfOrderFlag;
	}

	public void setOutOfOrderFlag(boolean outOfOrderFlag) {
		this.outOfOrderFlag = outOfOrderFlag;
	}

	@Column(name = "ServiceType", length = 1)
	public Character getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Character serviceType) {
		this.serviceType = serviceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicle")
	public Set<VehicleDriver> getVehicleDrivers() {
		return this.vehicleDrivers;
	}

	public void setVehicleDrivers(Set<VehicleDriver> vehicleDrivers) {
		this.vehicleDrivers = vehicleDrivers;
	}

}
