package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AspNetUserTokensId generated by hbm2java
 */
@Embeddable
public class AspNetUserTokensId implements java.io.Serializable {

	private Serializable userId;
	private Serializable loginProvider;
	private Serializable name;
	private Serializable value;

	public AspNetUserTokensId() {
	}

	public AspNetUserTokensId(Serializable userId, Serializable loginProvider, Serializable name) {
		this.userId = userId;
		this.loginProvider = loginProvider;
		this.name = name;
	}

	public AspNetUserTokensId(Serializable userId, Serializable loginProvider, Serializable name, Serializable value) {
		this.userId = userId;
		this.loginProvider = loginProvider;
		this.name = name;
		this.value = value;
	}

	@Column(name = "UserId", nullable = false)
	public Serializable getUserId() {
		return this.userId;
	}

	public void setUserId(Serializable userId) {
		this.userId = userId;
	}

	@Column(name = "LoginProvider", nullable = false)
	public Serializable getLoginProvider() {
		return this.loginProvider;
	}

	public void setLoginProvider(Serializable loginProvider) {
		this.loginProvider = loginProvider;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Value")
	public Serializable getValue() {
		return this.value;
	}

	public void setValue(Serializable value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AspNetUserTokensId))
			return false;
		AspNetUserTokensId castOther = (AspNetUserTokensId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getLoginProvider() == castOther.getLoginProvider())
						|| (this.getLoginProvider() != null && castOther.getLoginProvider() != null
								&& this.getLoginProvider().equals(castOther.getLoginProvider())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getLoginProvider() == null ? 0 : this.getLoginProvider().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
