package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AspNetUserClaims generated by hbm2java
 */
@Entity
@Table(name = "AspNetUserClaims", schema = "dbo", catalog = "onlineaccounting")
public class AspNetUserClaims implements java.io.Serializable {

	private int id;
	private AspNetUsers aspNetUsers;
	private Serializable claimType;
	private Serializable claimValue;

	public AspNetUserClaims() {
	}

	public AspNetUserClaims(int id, AspNetUsers aspNetUsers) {
		this.id = id;
		this.aspNetUsers = aspNetUsers;
	}

	public AspNetUserClaims(int id, AspNetUsers aspNetUsers, Serializable claimType, Serializable claimValue) {
		this.id = id;
		this.aspNetUsers = aspNetUsers;
		this.claimType = claimType;
		this.claimValue = claimValue;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public AspNetUsers getAspNetUsers() {
		return this.aspNetUsers;
	}

	public void setAspNetUsers(AspNetUsers aspNetUsers) {
		this.aspNetUsers = aspNetUsers;
	}

	@Column(name = "ClaimType")
	public Serializable getClaimType() {
		return this.claimType;
	}

	public void setClaimType(Serializable claimType) {
		this.claimType = claimType;
	}

	@Column(name = "ClaimValue")
	public Serializable getClaimValue() {
		return this.claimValue;
	}

	public void setClaimValue(Serializable claimValue) {
		this.claimValue = claimValue;
	}

}
