package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "City", schema = "dbo", catalog = "onlineaccounting")
public class City implements java.io.Serializable {

	private int id;
	private Country country;
	private Serializable name;
	private Set<District> districts = new HashSet<>(0);

	public City() {
	}

	public City(int id, Country country, Serializable name) {
		this.id = id;
		this.country = country;
		this.name = name;
	}

	public City(int id, Country country, Serializable name, Set<District> districts) {
		this.id = id;
		this.country = country;
		this.name = name;
		this.districts = districts;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CountryId", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<District> getProvinces() {
		return this.districts;
	}

	public void setProvinces(Set<District> districts) {
		this.districts = districts;
	}

}
