package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerDebit generated by hbm2java
 */
@Entity
@Table(name = "CustomerDebit", schema = "dbo", catalog = "onlineaccounting")
public class CustomerDebit implements java.io.Serializable {

	private int id;
	private Customer customer;
	private Serializable saleId;
	private Date dueDate;
	private BigDecimal totalDue;
	private char status;
	private boolean active;
	private Date lastUpdate;
	private Set<CustomerPayment> customerPayments = new HashSet<>(0);

	public CustomerDebit() {
	}

	public CustomerDebit(int id, Customer customer, Date dueDate, BigDecimal totalDue, char status, boolean active,
			Date lastUpdate) {
		this.id = id;
		this.customer = customer;
		this.dueDate = dueDate;
		this.totalDue = totalDue;
		this.status = status;
		this.active = active;
		this.lastUpdate = lastUpdate;
	}

	public CustomerDebit(int id, Customer customer, Serializable saleId, Date dueDate, BigDecimal totalDue, char status,
			boolean active, Date lastUpdate, Set<CustomerPayment> customerPayments) {
		this.id = id;
		this.customer = customer;
		this.saleId = saleId;
		this.dueDate = dueDate;
		this.totalDue = totalDue;
		this.status = status;
		this.active = active;
		this.lastUpdate = lastUpdate;
		this.customerPayments = customerPayments;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "SaleId")
	public Serializable getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Serializable saleId) {
		this.saleId = saleId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DueDate", nullable = false, length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "TotalDue", nullable = false, precision = 9)
	public BigDecimal getTotalDue() {
		return this.totalDue;
	}

	public void setTotalDue(BigDecimal totalDue) {
		this.totalDue = totalDue;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDebit")
	public Set<CustomerPayment> getCustomerPayments() {
		return this.customerPayments;
	}

	public void setCustomerPayments(Set<CustomerPayment> customerPayments) {
		this.customerPayments = customerPayments;
	}

}
