package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DeviceCodes generated by hbm2java
 */
@Entity
@Table(name = "DeviceCodes", schema = "dbo", catalog = "onlineaccounting", uniqueConstraints = @UniqueConstraint(columnNames = "DeviceCode"))
public class DeviceCodes implements java.io.Serializable {

	private Serializable userCode;
	private Serializable deviceCode;
	private Serializable subjectId;
	private Serializable sessionId;
	private Serializable clientId;
	private Serializable description;
	private Date creationTime;
	private Date expiration;
	private Serializable data;

	public DeviceCodes() {
	}

	public DeviceCodes(Serializable userCode, Serializable deviceCode, Serializable clientId, Date creationTime,
			Date expiration, Serializable data) {
		this.userCode = userCode;
		this.deviceCode = deviceCode;
		this.clientId = clientId;
		this.creationTime = creationTime;
		this.expiration = expiration;
		this.data = data;
	}

	public DeviceCodes(Serializable userCode, Serializable deviceCode, Serializable subjectId, Serializable sessionId,
			Serializable clientId, Serializable description, Date creationTime, Date expiration, Serializable data) {
		this.userCode = userCode;
		this.deviceCode = deviceCode;
		this.subjectId = subjectId;
		this.sessionId = sessionId;
		this.clientId = clientId;
		this.description = description;
		this.creationTime = creationTime;
		this.expiration = expiration;
		this.data = data;
	}

	@Id

	@Column(name = "UserCode", unique = true, nullable = false)
	public Serializable getUserCode() {
		return this.userCode;
	}

	public void setUserCode(Serializable userCode) {
		this.userCode = userCode;
	}

	@Column(name = "DeviceCode", unique = true, nullable = false)
	public Serializable getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(Serializable deviceCode) {
		this.deviceCode = deviceCode;
	}

	@Column(name = "SubjectId")
	public Serializable getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Serializable subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "SessionId")
	public Serializable getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Serializable sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "ClientId", nullable = false)
	public Serializable getClientId() {
		return this.clientId;
	}

	public void setClientId(Serializable clientId) {
		this.clientId = clientId;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreationTime", nullable = false, length = 27)
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Expiration", nullable = false, length = 27)
	public Date getExpiration() {
		return this.expiration;
	}

	public void setExpiration(Date expiration) {
		this.expiration = expiration;
	}

	@Column(name = "Data", nullable = false)
	public Serializable getData() {
		return this.data;
	}

	public void setData(Serializable data) {
		this.data = data;
	}

}
