package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeLeave generated by hbm2java
 */
@Entity
@Table(name = "EmployeeLeave", schema = "dbo", catalog = "onlineaccounting")
public class EmployeeLeave implements java.io.Serializable {

	private int id;
	private Employee employee;
	private Date laeveFrom;
	private Date leaveTo;
	private Date insertedAt;
	private boolean active;

	public EmployeeLeave() {
	}

	public EmployeeLeave(int id, Employee employee, Date laeveFrom, Date insertedAt, boolean active) {
		this.id = id;
		this.employee = employee;
		this.laeveFrom = laeveFrom;
		this.insertedAt = insertedAt;
		this.active = active;
	}

	public EmployeeLeave(int id, Employee employee, Date laeveFrom, Date leaveTo, Date insertedAt, boolean active) {
		this.id = id;
		this.employee = employee;
		this.laeveFrom = laeveFrom;
		this.leaveTo = leaveTo;
		this.insertedAt = insertedAt;
		this.active = active;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EmployeeId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LaeveFrom", nullable = false, length = 19)
	public Date getLaeveFrom() {
		return this.laeveFrom;
	}

	public void setLaeveFrom(Date laeveFrom) {
		this.laeveFrom = laeveFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LeaveTo", length = 19)
	public Date getLeaveTo() {
		return this.leaveTo;
	}

	public void setLeaveTo(Date leaveTo) {
		this.leaveTo = leaveTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InsertedAt", nullable = false, length = 19)
	public Date getInsertedAt() {
		return this.insertedAt;
	}

	public void setInsertedAt(Date insertedAt) {
		this.insertedAt = insertedAt;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
