package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "Merchant", schema = "dbo", catalog = "onlineaccounting")
public class Merchant implements java.io.Serializable {

	private String id;
	private MerchantType merchantType;
	private Serializable name;
	private Serializable commercialTitle;
	private Serializable tradeRegistrationId;
	private Serializable mersisId;
	private Serializable taxOffice;
	private Serializable taxpayerId;
	private Serializable iban;
	private Serializable liasonPerson;
	private Serializable liasonPhone;
	private Serializable phone;
	private Serializable web;
	private Date engagedOn;
	private Date lastUpdate;
	private boolean active;
	private Set<Vehicle> vehicles = new HashSet<>(0);
	private Set<DocumentInvoice> documentInvoices = new HashSet<>(0);
	private Set<Employee> employees = new HashSet<>(0);
	private Set<Product> products = new HashSet<>(0);
	private Set<MerchantAddress> merchantAddresses = new HashSet<>(0);
	private Set<Job> jobs = new HashSet<>(0);
	private Set<Sale> sales = new HashSet<>(0);
	private Set<Customer> customers = new HashSet<>(0);
	private Set<DocumentShipment> documentShipments = new HashSet<>(0);
	private Set<CashAccount> cashAccounts = new HashSet<>(0);

	public Merchant() {
	}

	public Merchant(String id, MerchantType merchantType, Serializable name, Serializable commercialTitle,
			Date engagedOn, Date lastUpdate, boolean active) {
		this.id = id;
		this.merchantType = merchantType;
		this.name = name;
		this.commercialTitle = commercialTitle;
		this.engagedOn = engagedOn;
		this.lastUpdate = lastUpdate;
		this.active = active;
	}

	public Merchant(String id, MerchantType merchantType, Serializable name, Serializable commercialTitle,
			Serializable tradeRegistrationId, Serializable mersisId, Serializable taxOffice, Serializable taxpayerId,
			Serializable iban, Serializable liasonPerson, Serializable liasonPhone, Serializable phone,
			Serializable web, Date engagedOn, Date lastUpdate, boolean active, Set<Vehicle> vehicles, Set<DocumentInvoice> documentInvoices,
			Set<Employee> employees, Set<Product> products, Set<MerchantAddress> merchantAddresses, Set<Job> jobs, Set<Sale> sales, Set<Customer> customers,
			Set<DocumentShipment> documentShipments, Set<CashAccount> cashAccounts) {
		this.id = id;
		this.merchantType = merchantType;
		this.name = name;
		this.commercialTitle = commercialTitle;
		this.tradeRegistrationId = tradeRegistrationId;
		this.mersisId = mersisId;
		this.taxOffice = taxOffice;
		this.taxpayerId = taxpayerId;
		this.iban = iban;
		this.liasonPerson = liasonPerson;
		this.liasonPhone = liasonPhone;
		this.phone = phone;
		this.web = web;
		this.engagedOn = engagedOn;
		this.lastUpdate = lastUpdate;
		this.active = active;
		this.vehicles = vehicles;
		this.documentInvoices = documentInvoices;
		this.employees = employees;
		this.products = products;
		this.merchantAddresses = merchantAddresses;
		this.jobs = jobs;
		this.sales = sales;
		this.customers = customers;
		this.documentShipments = documentShipments;
		this.cashAccounts = cashAccounts;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeId", nullable = false)
	public MerchantType getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(MerchantType merchantType) {
		this.merchantType = merchantType;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "CommercialTitle", nullable = false)
	public Serializable getCommercialTitle() {
		return this.commercialTitle;
	}

	public void setCommercialTitle(Serializable commercialTitle) {
		this.commercialTitle = commercialTitle;
	}

	@Column(name = "TradeRegistrationId")
	public Serializable getTradeRegistrationId() {
		return this.tradeRegistrationId;
	}

	public void setTradeRegistrationId(Serializable tradeRegistrationId) {
		this.tradeRegistrationId = tradeRegistrationId;
	}

	@Column(name = "MersisId")
	public Serializable getMersisId() {
		return this.mersisId;
	}

	public void setMersisId(Serializable mersisId) {
		this.mersisId = mersisId;
	}

	@Column(name = "TaxOffice")
	public Serializable getTaxOffice() {
		return this.taxOffice;
	}

	public void setTaxOffice(Serializable taxOffice) {
		this.taxOffice = taxOffice;
	}

	@Column(name = "TaxpayerId")
	public Serializable getTaxpayerId() {
		return this.taxpayerId;
	}

	public void setTaxpayerId(Serializable taxpayerId) {
		this.taxpayerId = taxpayerId;
	}

	@Column(name = "IBAN")
	public Serializable getIban() {
		return this.iban;
	}

	public void setIban(Serializable iban) {
		this.iban = iban;
	}

	@Column(name = "LiasonPerson")
	public Serializable getLiasonPerson() {
		return this.liasonPerson;
	}

	public void setLiasonPerson(Serializable liasonPerson) {
		this.liasonPerson = liasonPerson;
	}

	@Column(name = "LiasonPhone")
	public Serializable getLiasonPhone() {
		return this.liasonPhone;
	}

	public void setLiasonPhone(Serializable liasonPhone) {
		this.liasonPhone = liasonPhone;
	}

	@Column(name = "Phone")
	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	@Column(name = "Web")
	public Serializable getWeb() {
		return this.web;
	}

	public void setWeb(Serializable web) {
		this.web = web;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EngagedOn", nullable = false, length = 10)
	public Date getEngagedOn() {
		return this.engagedOn;
	}

	public void setEngagedOn(Date engagedOn) {
		this.engagedOn = engagedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 23)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<DocumentInvoice> getDocumentInvoices() {
		return this.documentInvoices;
	}

	public void setDocumentInvoices(Set<DocumentInvoice> documentInvoices) {
		this.documentInvoices = documentInvoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantAddress> getMerchantAddresses() {
		return this.merchantAddresses;
	}

	public void setMerchantAddresses(Set<MerchantAddress> merchantAddresses) {
		this.merchantAddresses = merchantAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Sale> getSales() {
		return this.sales;
	}

	public void setSales(Set<Sale> sales) {
		this.sales = sales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<DocumentShipment> getDocumentShipments() {
		return this.documentShipments;
	}

	public void setDocumentShipments(Set<DocumentShipment> documentShipments) {
		this.documentShipments = documentShipments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<CashAccount> getCashAccounts() {
		return this.cashAccounts;
	}

	public void setCashAccounts(Set<CashAccount> cashAccounts) {
		this.cashAccounts = cashAccounts;
	}

}
