package com.cayirozu.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shipment generated by hbm2java
 */
@Entity
@Table(name = "Shipment", schema = "dbo", catalog = "onlineaccounting")
public class Shipment implements java.io.Serializable {

	private int id;
	private ShipmentRoute shipmentRoute;
	private VehicleDriver vehicleDriver;
	private Date date;
	private Date timeStart;
	private Date timeEnd;
	private Integer odometerStart;
	private Integer odometerEnd;
	private char status;
	private Date lastUpdate;
	private boolean active;
	private Set<ShipmentLoad> shipmentLoads = new HashSet<>(0);

	public Shipment() {
	}

	public Shipment(int id, VehicleDriver vehicleDriver, Date date, char status, Date lastUpdate, boolean active) {
		this.id = id;
		this.vehicleDriver = vehicleDriver;
		this.date = date;
		this.status = status;
		this.lastUpdate = lastUpdate;
		this.active = active;
	}

	public Shipment(int id, ShipmentRoute shipmentRoute, VehicleDriver vehicleDriver, Date date, Date timeStart,
			Date timeEnd, Integer odometerStart, Integer odometerEnd, char status, Date lastUpdate, boolean active,
			Set<ShipmentLoad> shipmentLoads) {
		this.id = id;
		this.shipmentRoute = shipmentRoute;
		this.vehicleDriver = vehicleDriver;
		this.date = date;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.odometerStart = odometerStart;
		this.odometerEnd = odometerEnd;
		this.status = status;
		this.lastUpdate = lastUpdate;
		this.active = active;
		this.shipmentLoads = shipmentLoads;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ShipmentRouteId")
	public ShipmentRoute getShipmentRoute() {
		return this.shipmentRoute;
	}

	public void setShipmentRoute(ShipmentRoute shipmentRoute) {
		this.shipmentRoute = shipmentRoute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CarrierId", nullable = false)
	public VehicleDriver getVehicleDriver() {
		return this.vehicleDriver;
	}

	public void setVehicleDriver(VehicleDriver vehicleDriver) {
		this.vehicleDriver = vehicleDriver;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "TimeStart", length = 8)
	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "TimeEnd", length = 8)
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	@Column(name = "OdometerStart")
	public Integer getOdometerStart() {
		return this.odometerStart;
	}

	public void setOdometerStart(Integer odometerStart) {
		this.odometerStart = odometerStart;
	}

	@Column(name = "OdometerEnd")
	public Integer getOdometerEnd() {
		return this.odometerEnd;
	}

	public void setOdometerEnd(Integer odometerEnd) {
		this.odometerEnd = odometerEnd;
	}

	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipment")
	public Set<ShipmentLoad> getShipmentLoads() {
		return this.shipmentLoads;
	}

	public void setShipmentLoads(Set<ShipmentLoad> shipmentLoads) {
		this.shipmentLoads = shipmentLoads;
	}

}
