package com.bakery.management.db.entity;
// Generated 19 Ara 2020 06:35:03 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountTransaction generated by hbm2java
 */
@Entity
@Table(name = "CashTransaction", schema = "dbo", catalog = "onlineaccounting")
public class CashTransaction implements java.io.Serializable {

	private int id;
	private CashAccount cashAccount;
	private Date transactionDate;
	private char transactionType;
	private BigDecimal transactionAmount;
	private String explanation;
	private Date lastUpdate;
	private boolean active;

	public CashTransaction() {
	}

	public CashTransaction(int id, CashAccount cashAccount, Date transactionDate, char transactionType,
						   BigDecimal transactionAmount, String explanation, Date lastUpdate, boolean active) {
		this.id = id;
		this.cashAccount = cashAccount;
		this.transactionDate = transactionDate;
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.explanation = explanation;
		this.lastUpdate = lastUpdate;
		this.active = active;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CashAccountId", nullable = false)
	public CashAccount getCashAccount() {
		return this.cashAccount;
	}

	public void setCashAccount(CashAccount cashAccount) {
		this.cashAccount = cashAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransactionDate", nullable = false, length = 19)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "TransactionType", nullable = false, length = 1)
	public char getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(char transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "TransactionAmount", nullable = false, precision = 9)
	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	@Column(name = "Explanation", nullable = false)
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "Active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
